# Generated by Django 4.0.1 on 2022-01-11 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='user_img',
            field=models.ImageField(blank=True, upload_to='uploads'),
        ),
    ]
