# Generated by Django 4.0.1 on 2022-01-28 20:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='userRandomColor',
            field=models.CharField(default='#ffffff', max_length=7, validators=[django.core.validators.MinLengthValidator(7)]),
        ),
    ]
