# Generated by Django 4.0.1 on 2022-01-21 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='books',
            field=models.JSONField(default={}),
        ),
    ]
