# Generated by Django 4.0.1 on 2022-01-13 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_account_user_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('imgUrl', models.URLField()),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='books',
            field=models.ManyToManyField(to='main.Book'),
        ),
    ]
