# Generated by Django 4.0.1 on 2022-01-31 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_account_userrandomcolor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='account',
            name='books',
        ),
        migrations.AddField(
            model_name='account',
            name='books',
            field=models.ManyToManyField(to='main.Book'),
        ),
    ]
